export const data = [
  {
    id: "1",
    name: "Dalol Real Estate",
    project: "Gotera-Kera Area",
    price: "95,000",
    bedroom: 2,
    bathroom: 2,
    area: 72,
    images: [
      "/images/7.jpg",
      "/images/2.jpg",
      "/images/9.jpg",
      "/images/1.jpg",
      "/images/3.jpg",
      "/images/10.jpg",
      "/images/5.jpg",
      "/images/6.jpg",
    ],
    location: "Jacksonville, FL 32210",
  },
  {
    id: "2",
    name: "Abay Homes Real Estate",
    price: "100,000",
    bedroom: 3,
    bathroom: 2,
    area: 150,
    images: [
      "/images/2.jpg",
      "/images/9.jpg",
      "/images/1.jpg",
      "/images/3.jpg",
      "/images/10.jpg",
      "/images/5.jpg",
      "/images/6.jpg",
    ],
    location: "Altadena, CA 91001",
  },
  {
    id: "3",
    name: "22414 NAVASOTA CIR",
    price: "1,500,000",
    bedroom: 5,
    bathroom: 3,
    area: 250,
    images: [
      "/images/9.jpg",
      "/images/1.jpg",
      "/images/3.jpg",
      "/images/10.jpg",
      "/images/5.jpg",
      "/images/6.jpg",
    ],
    location: "San Antonio, TX 78259",
  },
  {
    id: "4",
    name: "9216 COXWELL Court",
    price: "650,000",
    bedroom: 2,
    bathroom: 1,
    area: 110,
    images: [
      "/images/1.jpg",
      "/images/3.jpg",
      "/images/10.jpg",
      "/images/5.jpg",
      "/images/6.jpg",
      "/images/7.jpg",
      "/images/2.jpg",
    ],
    location: "Jacksonville, FL 32210",
  },
  {
    id: "5",
    name: "18389 Verano St",
    price: "250,000",
    bedroom: 1,
    bathroom: 1,
    area: 56,
    images: [
      "/images/3.jpg",
      "/images/10.jpg",
      "/images/5.jpg",
      "/images/6.jpg",
      "/images/7.jpg",
      "/images/2.jpg",
      "/images/3.jpg",
      "/images/10.jpg",
      "/images/5.jpg",
      "/images/6.jpg",
      "/images/7.jpg",
      "/images/2.jpg",
    ],
    location: "Hesperia, CA 92345",
  },
  {
    id: "6",
    name: "25007 Summit Hollow",
    price: "380,000",
    bedroom: 2,
    bathroom: 1,
    area: 110,
    images: [
      "/images/10.jpg",
      "/images/7.jpg",
      "/images/2.jpg",
      "/images/9.jpg",
      "/images/1.jpg",
      "/images/3.jpg",
      "/images/5.jpg",
      "/images/6.jpg",
    ],
    location: "San Antonio, TX 78258",
  },
  {
    id: "7",
    name: "5455 W Ray Rd",
    price: "525,000",
    bedroom: 2,
    bathroom: 1,
    area: 110,
    images: [
      "/images/5.jpg",
      "/images/10.jpg",
      "/images/7.jpg",
      "/images/2.jpg",
      "/images/9.jpg",
      "/images/3.jpg",
      "/images/6.jpg",
    ],
    location: "Chandler, AZ 85226",
  },
  {
    id: "8",
    name: "7206 Bertram Ct",
    price: "700,000",
    bedroom: 3,
    bathroom: 2,
    area: 240,
    images: [
      "/images/6.jpg",
      "/images/10.jpg",
      "/images/7.jpg",
      "/images/5.jpg",
      "/images/2.jpg",
      "/images/9.jpg",
      "/images/1.jpg",
      "/images/3.jpg",
    ],
    location: "Austin, TX 78741",
  },
  {
    id: "9",
    name: "22414 NAVASOTA CIR",
    price: "1,500,000",
    bedroom: 5,
    bathroom: 3,
    area: 250,
    images: [
      "/images/9.jpg",
      "/images/1.jpg",
      "/images/3.jpg",
      "/images/10.jpg",
      "/images/5.jpg",
      "/images/6.jpg",
    ],
    location: "San Antonio, TX 78259",
  },
  {
    id: "10",
    name: "9216 COXWELL Court",
    price: "650,000",
    bedroom: 2,
    bathroom: 1,
    area: 110,
    images: [
      "/images/1.jpg",
      "/images/3.jpg",
      "/images/10.jpg",
      "/images/5.jpg",
      "/images/6.jpg",
      "/images/7.jpg",
      "/images/2.jpg",
    ],
    location: "Jacksonville, FL 32210",
  },
];
